### ISSUE TITLE
UndoManager adding extra characters to y-xml

### ISSUE THREAD

**Issue by twiss** [y-js/yjs#86]
In the html-editor example, if I type "Lorem ipsum dolor sit amet.", and then undo and redo (using the undoManager) it becomes:

    "Lorem ipsum dolor sit amet.    " or "Lorem ipsum dolor sit amet.     p "

Or, if I type slowly, then undo+redo part of the sentence, then undo+redo the entire sentence, it becomes:

    "Lorem ipsum dolor siitt a ammeett..        "

I usually clear and refresh the page between tries, if I don't, the results get a bit weirder still.

**Comment by dmonad** [comment]
Okay, you found it. This issue is already fixed in Yjs@13.0.0-51

**Comment by twiss** [comment]
Hi @dmonad, unfortunately I'm still seeing the issue exactly as before in v13.0.0-51 if I execute the steps outlined above. I'm using Chrome on Linux, so I had to slightly modify `interceptUndoRedo` to also accept `ctrlKey` instead of `metaKey`.

**Comment by dmonad** [comment]
Undo-redo definitely needs more love

**Comment by dmonad** [comment]
UndoManager got a major update and I can't reproduce this anymore.
